name: NodeJS with Webpack

on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 迁出代码
        uses: actions/checkout@main
      
      - name: 切换为pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 安装Node
        uses: actions/setup-node@main
        with:
          node-version: "20.x"
      
      - name: 安装依赖
        run: pnpm i

      - name: 打包
        run: npm run build

      - name: 发布到服务器
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr --delete --mkpath"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: root
          TARGET: /home/apps-root/blog-admin-2022
